//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ.
    /// </summary>
    // *** Start programmer edit section *** (документ CustomAttributes)

    // *** End programmer edit section *** (документ CustomAttributes)
    [AutoAltered()]
    [Caption("Документ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("документE", new string[] {
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'"})]
    [View("документL", new string[] {
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'"})]
    public class документ : ICSSoft.STORMNET.DataObject
    {
        
        private int fномер;
        
        private System.DateTime fдатазаполнения = System.DateTime.Now;
        
        // *** Start programmer edit section *** (документ CustomMembers)

        // *** End programmer edit section *** (документ CustomMembers)

        
        /// <summary>
        /// номер.
        /// </summary>
        // *** Start programmer edit section *** (документ.номер CustomAttributes)

        // *** End programmer edit section *** (документ.номер CustomAttributes)
        public virtual int номер
        {
            get
            {
                // *** Start programmer edit section *** (документ.номер Get start)

                // *** End programmer edit section *** (документ.номер Get start)
                int result = this.fномер;
                // *** Start programmer edit section *** (документ.номер Get end)

                // *** End programmer edit section *** (документ.номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (документ.номер Set start)

                // *** End programmer edit section *** (документ.номер Set start)
                this.fномер = value;
                // *** Start programmer edit section *** (документ.номер Set end)

                // *** End programmer edit section *** (документ.номер Set end)
            }
        }
        
        /// <summary>
        /// датазаполнения.
        /// </summary>
        // *** Start programmer edit section *** (документ.датазаполнения CustomAttributes)

        // *** End programmer edit section *** (документ.датазаполнения CustomAttributes)
        public virtual System.DateTime датазаполнения
        {
            get
            {
                // *** Start programmer edit section *** (документ.датазаполнения Get start)

                // *** End programmer edit section *** (документ.датазаполнения Get start)
                System.DateTime result = this.fдатазаполнения;
                // *** Start programmer edit section *** (документ.датазаполнения Get end)

                // *** End programmer edit section *** (документ.датазаполнения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (документ.датазаполнения Set start)

                // *** End programmer edit section *** (документ.датазаполнения Set start)
                this.fдатазаполнения = value;
                // *** Start programmer edit section *** (документ.датазаполнения Set end)

                // *** End programmer edit section *** (документ.датазаполнения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "документE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View документE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("документE", typeof(IIS.АСУ_склад.документ));
                }
            }
            
            /// <summary>
            /// "документL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View документL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("документL", typeof(IIS.АСУ_склад.документ));
                }
            }
        }
    }
}
