//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (заказ CustomAttributes)

    // *** End programmer edit section *** (заказ CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("заказE", new string[] {
            "статус as \'Статус\'",
            "датаОтгрузки as \'Дата отгрузки\'",
            "датаОплаты as \'Дата оплаты\'",
            "цена as \'Цена\'",
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'",
            "менеджер as \'Менеджер\'",
            "менеджер.фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("заказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [View("заказL", new string[] {
            "статус as \'Статус\'",
            "датаОтгрузки as \'Дата отгрузки\'",
            "датаОплаты as \'Дата оплаты\'",
            "цена as \'Цена\'",
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'",
            "менеджер.фамилия as \'Фамилия\'"})]
    public class заказ : IIS.АСУ_склад.документ
    {
        
        private IIS.АСУ_склад.состояниезаказа fстатус;
        
        private System.DateTime fдатаОтгрузки;
        
        private System.DateTime fдатаОплаты;
        
        private double fцена;
        
        private IIS.АСУ_склад.Сотрудник fменеджер;
        
        private IIS.АСУ_склад.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (заказ CustomMembers)

        // *** End programmer edit section *** (заказ CustomMembers)

        
        /// <summary>
        /// статус.
        /// </summary>
        // *** Start programmer edit section *** (заказ.статус CustomAttributes)

        // *** End programmer edit section *** (заказ.статус CustomAttributes)
        public virtual IIS.АСУ_склад.состояниезаказа статус
        {
            get
            {
                // *** Start programmer edit section *** (заказ.статус Get start)

                // *** End programmer edit section *** (заказ.статус Get start)
                IIS.АСУ_склад.состояниезаказа result = this.fстатус;
                // *** Start programmer edit section *** (заказ.статус Get end)

                // *** End programmer edit section *** (заказ.статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.статус Set start)

                // *** End programmer edit section *** (заказ.статус Set start)
                this.fстатус = value;
                // *** Start programmer edit section *** (заказ.статус Set end)

                // *** End programmer edit section *** (заказ.статус Set end)
            }
        }
        
        /// <summary>
        /// датаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (заказ.датаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (заказ.датаОтгрузки CustomAttributes)
        public virtual System.DateTime датаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (заказ.датаОтгрузки Get start)

                // *** End programmer edit section *** (заказ.датаОтгрузки Get start)
                System.DateTime result = this.fдатаОтгрузки;
                // *** Start programmer edit section *** (заказ.датаОтгрузки Get end)

                // *** End programmer edit section *** (заказ.датаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.датаОтгрузки Set start)

                // *** End programmer edit section *** (заказ.датаОтгрузки Set start)
                this.fдатаОтгрузки = value;
                // *** Start programmer edit section *** (заказ.датаОтгрузки Set end)

                // *** End programmer edit section *** (заказ.датаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// датаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (заказ.датаОплаты CustomAttributes)

        // *** End programmer edit section *** (заказ.датаОплаты CustomAttributes)
        public virtual System.DateTime датаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (заказ.датаОплаты Get start)

                // *** End programmer edit section *** (заказ.датаОплаты Get start)
                System.DateTime result = this.fдатаОплаты;
                // *** Start programmer edit section *** (заказ.датаОплаты Get end)

                // *** End programmer edit section *** (заказ.датаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.датаОплаты Set start)

                // *** End programmer edit section *** (заказ.датаОплаты Set start)
                this.fдатаОплаты = value;
                // *** Start programmer edit section *** (заказ.датаОплаты Set end)

                // *** End programmer edit section *** (заказ.датаОплаты Set end)
            }
        }
        
        /// <summary>
        /// цена.
        /// </summary>
        // *** Start programmer edit section *** (заказ.цена CustomAttributes)

        // *** End programmer edit section *** (заказ.цена CustomAttributes)
        public virtual double цена
        {
            get
            {
                // *** Start programmer edit section *** (заказ.цена Get start)

                // *** End programmer edit section *** (заказ.цена Get start)
                double result = this.fцена;
                // *** Start programmer edit section *** (заказ.цена Get end)

                // *** End programmer edit section *** (заказ.цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.цена Set start)

                // *** End programmer edit section *** (заказ.цена Set start)
                this.fцена = value;
                // *** Start programmer edit section *** (заказ.цена Set end)

                // *** End programmer edit section *** (заказ.цена Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (заказ.менеджер CustomAttributes)

        // *** End programmer edit section *** (заказ.менеджер CustomAttributes)
        [NotNull()]
        public virtual IIS.АСУ_склад.Сотрудник менеджер
        {
            get
            {
                // *** Start programmer edit section *** (заказ.менеджер Get start)

                // *** End programmer edit section *** (заказ.менеджер Get start)
                IIS.АСУ_склад.Сотрудник result = this.fменеджер;
                // *** Start programmer edit section *** (заказ.менеджер Get end)

                // *** End programmer edit section *** (заказ.менеджер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.менеджер Set start)

                // *** End programmer edit section *** (заказ.менеджер Set start)
                this.fменеджер = value;
                // *** Start programmer edit section *** (заказ.менеджер Set end)

                // *** End programmer edit section *** (заказ.менеджер Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.АСУ_склад.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.АСУ_склад.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.АСУ_склад.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (заказ.СтрокаЗаказа Set end)
            }
        }
        
        // *** Start programmer edit section *** (заказ.отменить CustomAttributes)

        // *** End programmer edit section *** (заказ.отменить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void отменить()
        {
            // *** Start programmer edit section *** (заказ.отменить method implementation)
            return;
            // *** End programmer edit section *** (заказ.отменить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "заказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View заказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("заказE", typeof(IIS.АСУ_склад.заказ));
                }
            }
            
            /// <summary>
            /// "заказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View заказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("заказL", typeof(IIS.АСУ_склад.заказ));
                }
            }
        }
    }
}
