//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (накладная CustomAttributes)

    // *** End programmer edit section *** (накладная CustomAttributes)
    [AutoAltered()]
    [Caption("Накладная")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("накладнаяE", new string[] {
            "статус as \'Статус\'",
            "датаВремяОтгрузки as \'Дата время отгрузки\'",
            "сумма as \'Сумма\'",
            "вес as \'Вес\'",
            "примечание as \'Примечание\'",
            "ФИОполучателя as \'Ф и ополучателя\'",
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'",
            "материальноОтветственноеЛицо as \'Материально ответственное лицо\'",
            "материальноОтветственноеЛицо.фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("накладнаяE", "записьвнакладной", "записьвнакладнойE", true, "", "Записьвнакладной", true, new string[] {
            ""})]
    [View("накладнаяL", new string[] {
            "статус as \'Статус\'",
            "датаВремяОтгрузки as \'Дата время отгрузки\'",
            "сумма as \'Сумма\'",
            "вес as \'Вес\'",
            "примечание as \'Примечание\'",
            "ФИОполучателя as \'Ф и ополучателя\'",
            "номер as \'Номер\'",
            "датазаполнения as \'Датазаполнения\'",
            "материальноОтветственноеЛицо.фамилия as \'Фамилия\'"})]
    public class накладная : IIS.АСУ_склад.документ
    {
        
        private IIS.АСУ_склад.состояниенакладной fстатус;
        
        private System.DateTime fдатаВремяОтгрузки;
        
        private double fсумма;
        
        private double fвес;
        
        private string fпримечание;
        
        private string fФИОполучателя;
        
        private IIS.АСУ_склад.Сотрудник fматериальноОтветственноеЛицо;
        
        private IIS.АСУ_склад.DetailArrayOfзаписьвнакладной fзаписьвнакладной;
        
        // *** Start programmer edit section *** (накладная CustomMembers)

        // *** End programmer edit section *** (накладная CustomMembers)

        
        /// <summary>
        /// статус.
        /// </summary>
        // *** Start programmer edit section *** (накладная.статус CustomAttributes)

        // *** End programmer edit section *** (накладная.статус CustomAttributes)
        public virtual IIS.АСУ_склад.состояниенакладной статус
        {
            get
            {
                // *** Start programmer edit section *** (накладная.статус Get start)

                // *** End programmer edit section *** (накладная.статус Get start)
                IIS.АСУ_склад.состояниенакладной result = this.fстатус;
                // *** Start programmer edit section *** (накладная.статус Get end)

                // *** End programmer edit section *** (накладная.статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.статус Set start)

                // *** End programmer edit section *** (накладная.статус Set start)
                this.fстатус = value;
                // *** Start programmer edit section *** (накладная.статус Set end)

                // *** End programmer edit section *** (накладная.статус Set end)
            }
        }
        
        /// <summary>
        /// датаВремяОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (накладная.датаВремяОтгрузки CustomAttributes)

        // *** End programmer edit section *** (накладная.датаВремяОтгрузки CustomAttributes)
        public virtual System.DateTime датаВремяОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (накладная.датаВремяОтгрузки Get start)

                // *** End programmer edit section *** (накладная.датаВремяОтгрузки Get start)
                System.DateTime result = this.fдатаВремяОтгрузки;
                // *** Start programmer edit section *** (накладная.датаВремяОтгрузки Get end)

                // *** End programmer edit section *** (накладная.датаВремяОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.датаВремяОтгрузки Set start)

                // *** End programmer edit section *** (накладная.датаВремяОтгрузки Set start)
                this.fдатаВремяОтгрузки = value;
                // *** Start programmer edit section *** (накладная.датаВремяОтгрузки Set end)

                // *** End programmer edit section *** (накладная.датаВремяОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// сумма.
        /// </summary>
        // *** Start programmer edit section *** (накладная.сумма CustomAttributes)

        // *** End programmer edit section *** (накладная.сумма CustomAttributes)
        public virtual double сумма
        {
            get
            {
                // *** Start programmer edit section *** (накладная.сумма Get start)

                // *** End programmer edit section *** (накладная.сумма Get start)
                double result = this.fсумма;
                // *** Start programmer edit section *** (накладная.сумма Get end)

                // *** End programmer edit section *** (накладная.сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.сумма Set start)

                // *** End programmer edit section *** (накладная.сумма Set start)
                this.fсумма = value;
                // *** Start programmer edit section *** (накладная.сумма Set end)

                // *** End programmer edit section *** (накладная.сумма Set end)
            }
        }
        
        /// <summary>
        /// вес.
        /// </summary>
        // *** Start programmer edit section *** (накладная.вес CustomAttributes)

        // *** End programmer edit section *** (накладная.вес CustomAttributes)
        public virtual double вес
        {
            get
            {
                // *** Start programmer edit section *** (накладная.вес Get start)

                // *** End programmer edit section *** (накладная.вес Get start)
                double result = this.fвес;
                // *** Start programmer edit section *** (накладная.вес Get end)

                // *** End programmer edit section *** (накладная.вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.вес Set start)

                // *** End programmer edit section *** (накладная.вес Set start)
                this.fвес = value;
                // *** Start programmer edit section *** (накладная.вес Set end)

                // *** End programmer edit section *** (накладная.вес Set end)
            }
        }
        
        /// <summary>
        /// примечание.
        /// </summary>
        // *** Start programmer edit section *** (накладная.примечание CustomAttributes)

        // *** End programmer edit section *** (накладная.примечание CustomAttributes)
        [StrLen(255)]
        public virtual string примечание
        {
            get
            {
                // *** Start programmer edit section *** (накладная.примечание Get start)

                // *** End programmer edit section *** (накладная.примечание Get start)
                string result = this.fпримечание;
                // *** Start programmer edit section *** (накладная.примечание Get end)

                // *** End programmer edit section *** (накладная.примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.примечание Set start)

                // *** End programmer edit section *** (накладная.примечание Set start)
                this.fпримечание = value;
                // *** Start programmer edit section *** (накладная.примечание Set end)

                // *** End programmer edit section *** (накладная.примечание Set end)
            }
        }
        
        /// <summary>
        /// ФИОполучателя.
        /// </summary>
        // *** Start programmer edit section *** (накладная.ФИОполучателя CustomAttributes)

        // *** End programmer edit section *** (накладная.ФИОполучателя CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОполучателя
        {
            get
            {
                // *** Start programmer edit section *** (накладная.ФИОполучателя Get start)

                // *** End programmer edit section *** (накладная.ФИОполучателя Get start)
                string result = this.fФИОполучателя;
                // *** Start programmer edit section *** (накладная.ФИОполучателя Get end)

                // *** End programmer edit section *** (накладная.ФИОполучателя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.ФИОполучателя Set start)

                // *** End programmer edit section *** (накладная.ФИОполучателя Set start)
                this.fФИОполучателя = value;
                // *** Start programmer edit section *** (накладная.ФИОполучателя Set end)

                // *** End programmer edit section *** (накладная.ФИОполучателя Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (накладная.материальноОтветственноеЛицо CustomAttributes)

        // *** End programmer edit section *** (накладная.материальноОтветственноеЛицо CustomAttributes)
        [NotNull()]
        public virtual IIS.АСУ_склад.Сотрудник материальноОтветственноеЛицо
        {
            get
            {
                // *** Start programmer edit section *** (накладная.материальноОтветственноеЛицо Get start)

                // *** End programmer edit section *** (накладная.материальноОтветственноеЛицо Get start)
                IIS.АСУ_склад.Сотрудник result = this.fматериальноОтветственноеЛицо;
                // *** Start programmer edit section *** (накладная.материальноОтветственноеЛицо Get end)

                // *** End programmer edit section *** (накладная.материальноОтветственноеЛицо Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.материальноОтветственноеЛицо Set start)

                // *** End programmer edit section *** (накладная.материальноОтветственноеЛицо Set start)
                this.fматериальноОтветственноеЛицо = value;
                // *** Start programmer edit section *** (накладная.материальноОтветственноеЛицо Set end)

                // *** End programmer edit section *** (накладная.материальноОтветственноеЛицо Set end)
            }
        }
        
        /// <summary>
        /// Накладная.
        /// </summary>
        // *** Start programmer edit section *** (накладная.записьвнакладной CustomAttributes)

        // *** End programmer edit section *** (накладная.записьвнакладной CustomAttributes)
        public virtual IIS.АСУ_склад.DetailArrayOfзаписьвнакладной записьвнакладной
        {
            get
            {
                // *** Start programmer edit section *** (накладная.записьвнакладной Get start)

                // *** End programmer edit section *** (накладная.записьвнакладной Get start)
                if ((this.fзаписьвнакладной == null))
                {
                    this.fзаписьвнакладной = new IIS.АСУ_склад.DetailArrayOfзаписьвнакладной(this);
                }
                IIS.АСУ_склад.DetailArrayOfзаписьвнакладной result = this.fзаписьвнакладной;
                // *** Start programmer edit section *** (накладная.записьвнакладной Get end)

                // *** End programmer edit section *** (накладная.записьвнакладной Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (накладная.записьвнакладной Set start)

                // *** End programmer edit section *** (накладная.записьвнакладной Set start)
                this.fзаписьвнакладной = value;
                // *** Start programmer edit section *** (накладная.записьвнакладной Set end)

                // *** End programmer edit section *** (накладная.записьвнакладной Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "накладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View накладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("накладнаяE", typeof(IIS.АСУ_склад.накладная));
                }
            }
            
            /// <summary>
            /// "накладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View накладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("накладнаяL", typeof(IIS.АСУ_склад.накладная));
                }
            }
        }
    }
}
