//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояниезаказа.
    /// </summary>
    // *** Start programmer edit section *** (состояниезаказа CustomAttributes)

    // *** End programmer edit section *** (состояниезаказа CustomAttributes)
    public enum состояниезаказа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниезаказа.новый CustomAttributes)

        // *** End programmer edit section *** (состояниезаказа.новый CustomAttributes)
        новый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниезаказа.оплаченный CustomAttributes)

        // *** End programmer edit section *** (состояниезаказа.оплаченный CustomAttributes)
        оплаченный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниезаказа.отменённый CustomAttributes)

        // *** End programmer edit section *** (состояниезаказа.отменённый CustomAttributes)
        отменённый,
    }
}
