//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояниенакладной.
    /// </summary>
    // *** Start programmer edit section *** (состояниенакладной CustomAttributes)

    // *** End programmer edit section *** (состояниенакладной CustomAttributes)
    public enum состояниенакладной
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниенакладной.новая CustomAttributes)

        // *** End programmer edit section *** (состояниенакладной.новая CustomAttributes)
        новая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниенакладной.выписанная CustomAttributes)

        // *** End programmer edit section *** (состояниенакладной.выписанная CustomAttributes)
        выписанная,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниенакладной.приостановленная CustomAttributes)

        // *** End programmer edit section *** (состояниенакладной.приостановленная CustomAttributes)
        приостановленная,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниенакладной.готовая CustomAttributes)

        // *** End programmer edit section *** (состояниенакладной.готовая CustomAttributes)
        готовая,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (состояниенакладной.отгруженная CustomAttributes)

        // *** End programmer edit section *** (состояниенакладной.отгруженная CustomAttributes)
        отгруженная,
    }
}
