//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "кодТовара as \'Код товара\'",
            "название as \'Название\'",
            "едицинаИзмерения as \'Едицина измерения\'",
            "описание as \'Описание\'",
            "цена as \'Цена\'"})]
    [View("ТоварL", new string[] {
            "кодТовара as \'Код товара\'",
            "название as \'Название\'",
            "едицинаИзмерения as \'Едицина измерения\'",
            "описание as \'Описание\'",
            "цена as \'Цена\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fкодТовара;
        
        private string fназвание;
        
        private string fедицинаИзмерения;
        
        private string fописание;
        
        private double fцена;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// кодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.кодТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.кодТовара CustomAttributes)
        public virtual int кодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.кодТовара Get start)

                // *** End programmer edit section *** (Товар.кодТовара Get start)
                int result = this.fкодТовара;
                // *** Start programmer edit section *** (Товар.кодТовара Get end)

                // *** End programmer edit section *** (Товар.кодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.кодТовара Set start)

                // *** End programmer edit section *** (Товар.кодТовара Set start)
                this.fкодТовара = value;
                // *** Start programmer edit section *** (Товар.кодТовара Set end)

                // *** End programmer edit section *** (Товар.кодТовара Set end)
            }
        }
        
        /// <summary>
        /// название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.название CustomAttributes)

        // *** End programmer edit section *** (Товар.название CustomAttributes)
        [StrLen(255)]
        public virtual string название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.название Get start)

                // *** End programmer edit section *** (Товар.название Get start)
                string result = this.fназвание;
                // *** Start programmer edit section *** (Товар.название Get end)

                // *** End programmer edit section *** (Товар.название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.название Set start)

                // *** End programmer edit section *** (Товар.название Set start)
                this.fназвание = value;
                // *** Start programmer edit section *** (Товар.название Set end)

                // *** End programmer edit section *** (Товар.название Set end)
            }
        }
        
        /// <summary>
        /// едицинаИзмерения.
        /// </summary>
        // *** Start programmer edit section *** (Товар.едицинаИзмерения CustomAttributes)

        // *** End programmer edit section *** (Товар.едицинаИзмерения CustomAttributes)
        [StrLen(255)]
        public virtual string едицинаИзмерения
        {
            get
            {
                // *** Start programmer edit section *** (Товар.едицинаИзмерения Get start)

                // *** End programmer edit section *** (Товар.едицинаИзмерения Get start)
                string result = this.fедицинаИзмерения;
                // *** Start programmer edit section *** (Товар.едицинаИзмерения Get end)

                // *** End programmer edit section *** (Товар.едицинаИзмерения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.едицинаИзмерения Set start)

                // *** End programmer edit section *** (Товар.едицинаИзмерения Set start)
                this.fедицинаИзмерения = value;
                // *** Start programmer edit section *** (Товар.едицинаИзмерения Set end)

                // *** End programmer edit section *** (Товар.едицинаИзмерения Set end)
            }
        }
        
        /// <summary>
        /// описание.
        /// </summary>
        // *** Start programmer edit section *** (Товар.описание CustomAttributes)

        // *** End programmer edit section *** (Товар.описание CustomAttributes)
        [StrLen(255)]
        public virtual string описание
        {
            get
            {
                // *** Start programmer edit section *** (Товар.описание Get start)

                // *** End programmer edit section *** (Товар.описание Get start)
                string result = this.fописание;
                // *** Start programmer edit section *** (Товар.описание Get end)

                // *** End programmer edit section *** (Товар.описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.описание Set start)

                // *** End programmer edit section *** (Товар.описание Set start)
                this.fописание = value;
                // *** Start programmer edit section *** (Товар.описание Set end)

                // *** End programmer edit section *** (Товар.описание Set end)
            }
        }
        
        /// <summary>
        /// цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.цена CustomAttributes)

        // *** End programmer edit section *** (Товар.цена CustomAttributes)
        public virtual double цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.цена Get start)

                // *** End programmer edit section *** (Товар.цена Get start)
                double result = this.fцена;
                // *** Start programmer edit section *** (Товар.цена Get end)

                // *** End programmer edit section *** (Товар.цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.цена Set start)

                // *** End programmer edit section *** (Товар.цена Set start)
                this.fцена = value;
                // *** Start programmer edit section *** (Товар.цена Set end)

                // *** End programmer edit section *** (Товар.цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.АСУ_склад.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.АСУ_склад.Товар));
                }
            }
        }
    }
}
