//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.АСУ_склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар на складе.
    /// </summary>
    // *** Start programmer edit section *** (ТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (ТоварНаСкладе CustomAttributes)
    [AutoAltered()]
    [Caption("Товар на складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварНаСкладеE", new string[] {
            "количество as \'Количество\'",
            "Товар as \'Товар\'",
            "Товар.название as \'Название\'"}, Hidden=new string[] {
            "Товар.название"})]
    [MasterViewDefineAttribute("ТоварНаСкладеE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "название")]
    public class ТоварНаСкладе : ICSSoft.STORMNET.DataObject
    {
        
        private int fколичество;
        
        private IIS.АСУ_склад.Товар fТовар;
        
        private IIS.АСУ_склад.склад fсклад;
        
        // *** Start programmer edit section *** (ТоварНаСкладе CustomMembers)

        // *** End programmer edit section *** (ТоварНаСкладе CustomMembers)

        
        /// <summary>
        /// количество.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.количество CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.количество CustomAttributes)
        public virtual int количество
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.количество Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.количество Get start)
                int result = this.fколичество;
                // *** Start programmer edit section *** (ТоварНаСкладе.количество Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.количество Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.количество Set start)
                this.fколичество = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.количество Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.количество Set end)
            }
        }
        
        /// <summary>
        /// Товар на складе.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Товар CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Товар CustomAttributes)
        [NotNull()]
        public virtual IIS.АСУ_склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Get start)
                IIS.АСУ_склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Товар Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.АСУ_склад.склад.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.склад CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.склад CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.АСУ_склад.склад склад
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.склад Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.склад Get start)
                IIS.АСУ_склад.склад result = this.fсклад;
                // *** Start programmer edit section *** (ТоварНаСкладе.склад Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.склад Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.склад Set start)
                this.fсклад = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.склад Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварНаСкладеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварНаСкладеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварНаСкладеE", typeof(IIS.АСУ_склад.ТоварНаСкладе));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТоварНаСкладе.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)
    public class DetailArrayOfТоварНаСкладе : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.АСУ_склад.DetailArrayOfТоварНаСкладе members)

        // *** End programmer edit section *** (IIS.АСУ_склад.DetailArrayOfТоварНаСкладе members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТоварНаСкладе by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТоварНаСкладе.
        /// </summary>
        public DetailArrayOfТоварНаСкладе(IIS.АСУ_склад.склад fсклад) : 
                base(typeof(ТоварНаСкладе), ((ICSSoft.STORMNET.DataObject)(fсклад)))
        {
        }
        
        public IIS.АСУ_склад.ТоварНаСкладе this[int index]
        {
            get
            {
                return ((IIS.АСУ_склад.ТоварНаСкладе)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.АСУ_склад.ТоварНаСкладе dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
