/*flexberryautogenerated="true"*/
namespace IIS.АСУ_склад
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class документL : BaseListForm<документ>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public документL() : base(документ.Views.документL)
        {
            EditPage = документE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/dokument/dokumentL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
